### ISSUE TITLE
Exception on new Plone 4.3 setup

### ISSUE THREAD

**Issue by rodfersou** [collective/sc.contentrules.localrole#16]
This exception happen on Plone 4.3 when try to start the instance.

```python
Traceback (most recent call last):
  File "/home/rodfersou/.projects/sc.contentrules.localrole.4/parts/instance/bin/interpreter", line 278, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/rodfersou/.projects/cache/eggs/Zope2-2.13.28-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/rodfersou/.projects/cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/home/rodfersou/.projects/cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 620, in execute_actions
    for action in resolveConflicts(self.actions):
  File "/home/rodfersou/.projects/cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1527, in resolveConflicts
    raise ConfigurationConflictError(conflicts)
zope.configuration.config.ConfigurationConflictError: Conflicting configuration actions
  For: ('adapter', (<class 'zope.interface.exceptions.Invalid'>, <InterfaceClass zope.publisher.interfaces.browser.IBrowserRequest>), <InterfaceClass zope.formlib.interfaces.IWidgetInputErrorView>, '')
    File "/home/rodfersou/.projects/cache/eggs/five.formlib-1.0.4-py2.7.egg/five/formlib/configure.zcml", line 22.4-27.10
          <adapter
              for="zope.interface.Invalid
                   zope.publisher.interfaces.browser.IBrowserRequest"
              factory=".errors.InvalidErrorView"
              permission="zope.Public"
              />
    File "/home/rodfersou/.projects/cache/eggs/zope.formlib-4.3.0-py2.7.egg/zope/formlib/configure.zcml", line 22.2-25.4
        <adapter
          factory=".errors.InvalidErrorView"
          permission="zope.Public"
        />
```

**Comment by rodfersou** [comment]
@instification maybe we need to pin the version of zope.formlib for Plone 4.3

**Comment by rodfersou** [comment]
weird.. I don't figure out why got this exception.. both configuration have years untouched..
